*** Variables ***
${url}    https://www.google.co.th
${text1}     Candy
${text2}     intro robot framework
${url3}    https://www.browserstack.com/guide/robot-framework-guide
${url4}    https://medium.com/@aifakhri/brief-intro-to-robot-framework-and-extending-robot-framework-with-python-7c8b795dca7f
${url5}    https://testautomationu.applitools.com/robot-framework-tutorial/chapter1.html
@{list}    ${url3}    ${url4}    ${url5}

